### ISSUE TITLE
Making renpass citable

### ISSUE THREAD

**Issue by simnh** [znes/renpass#10]
We could make renpass citable by linking this repository to a open-science framework renpass-gis account. What do you think?

**Comment by ckaldemeyer** [comment]
> We could make renpass citable by linking this repository to a open-science framework renpass-gis account. What do you think?

Nice idea! Do you want to go ahead?

**Comment by simnh** [comment]
yeah I can do it..

**Comment by ckaldemeyer** [comment]
:+1:  Thanks!

**Comment by simnh** [comment]
You both have to register yourself, as I created the project I then can add you as contributors...

**Comment by ckaldemeyer** [comment]
@s3pp : You can already register at https://osf.io/

I'll probably write the mail tomorrow and ask if everybody is fine with our plans. If there are no objections, we can create the DOI.

**Comment by ckaldemeyer** [comment]
I have invited @cswh and published the enty. Feel free to change it

**Comment by simnh** [comment]
Should we not add a tag for the release merge ? This then must somehow link to the doi...or are you still working on this?
