### ISSUE TITLE
Finish documentation

### ISSUE THREAD

**Issue by ckaldemeyer** [znes/renpass#13]
I have added my latest improvements to dev: https://github.com/znes/renpass_gis/tree/dev

@s3pp : Once the command line option (#9) has been implemented, it has to integrated in the Usage-Section

@simnh : Any suggestions?

**Comment by simnh** [comment]
Ok so missing is still the CSV-reader docu from oemof, right? And I had something to wrote about something I forgot... flows or so?

**Comment by ckaldemeyer** [comment]
I have now linked the CSV-reader in the "Usage" chapter.

**Comment by ckaldemeyer** [comment]
Maybe we just also link the flow-concept/documentation as soon as you have documented the flow class?

I think this was what you were planning to do if I remember it right..

**Comment by ckaldemeyer** [comment]
I have added a "Credits" section now:


Credits
=======

Oemof and renpassG!S are community projects and have been realised in collaborative work.
We therefore thank all people who contributed to the framework and the scenario development,
and in particular the following people for their contributions to this first version of renpassG!S:

* Simon Hilpert and Uwe Krien for the effort they put in the oemof-refactoring
* Wolf-Dieter Bunke and Marion Christ for the initial scenario development
* Clemens Wingenbach and Stephan Günther for providing the prior version
* Frauke Wiese and Gesine Bökenkamp for creating `renpass <http://www.renpass.eu>`_
* All people at the Center for Sustainable Energy Systems (ZNES) Flensburg

Maybe this seems a bit over the top but I think it's on the one hand a nice gesture to worship the work of all people that contributed and on the other hand attributes the work to the people that were involved..

If you are all fine with the documentation I would also send an internal e-mail to all people involved at ZNES to get some feedback. Also to involve everybody in case that somebody is not happy..

What do you think?

**Comment by ckaldemeyer** [comment]
I have also changed the overview figure to make it a bit more generic:

* load/wheather data in arbitrary resolution

Instead of:

* ENTSO-E load profiles and wheather data in hourly resolution

**Comment by ckaldemeyer** [comment]
Everything seems to be fine now. The flow concept, etc. can be added to the documentation/paper
