### ISSUE TITLE
geoJSON support for scenario description

### ISSUE THREAD

**Issue by ckaldemeyer** [znes/renpass#17]
This might be cool for the data repository like interactive browsing of country data or installed capacities.

Example (we could already link it from README.rst): https://github.com/ckaldemeyer/sandbox/blob/master/test.geojson

Even better would be to embed it into the README which I have just asked: http://stackoverflow.com/questions/40866459/embed-rendered-geojson-files-in-readme-rst-restructuredtext-on-github

This is of course for later, later. But I think it would be cool. What do you think?

**Comment by eosram** [comment]
I think this feature is really useful. Thanks for sharing! Unfortunately I also haven't found a solution to embed the geoJSON in a README.rst and no one answered on stackoverflow yet. In the meantime I created a more comprehensive [Example](https://github.com/znes/cFlEnS/blob/feature/open_eGo-scenarios/open_eGo/modelpowerplants.geojson) though.

**Comment by eosram** [comment]
I will close the issue, because it refers to the data repository.

**Comment by ckaldemeyer** [comment]
I think that @wolfbunke mentioned that it's possible to render complete HTML pages via github.io. If we converted the README to HTML it would allow us to include geojson via IFRAMES or even HTML5. 

But I would recommend that we only do stuff that's needed in the first place and this is really only "Nice to have".. ;-)
