### ISSUE TITLE
Remove label specific result processing

### ISSUE THREAD

**Issue by ckaldemeyer** [znes/renpass#19]

**Comment by ckaldemeyer** [comment]
I would like to change/remove everything after

        # postprocessing: write dispatch and prices for all regions to file system

to make the App label/structure agnostic.

@s3pp, @simnh : Would it be an option to just do a "flat unstacking" in the first place and ignore the not explicitly names storages as a hotfix?

So all busses would be saved as CSV, including the resource busses. An if there are 3 timeseries per storage they are named like storage, storage.1, storage.2 from pandas and the user has to find out which one is the filling level, the input and output.

I think it would be a compromise for a hotfix until the resultdataframe is remastered. At least, all kinds of scenarios (also MENA, ...) could be calculated this way..

**Comment by simnh** [comment]
>...storage, storage.1, storage.2 from pandas and the user has to find out which one is the filling level, the input and output.

I think leaving it to the user is not very good...for now it works, we could move the code away from the main file to make it 'clean'. 
But generally, we should rather tackle the solph/outputlib problem soon. the label 'other' is not great either ;) maybe this one can be 'filling_level' or just level. We really need to work on this...

But I like the idea of full bus balances though.

**Comment by simnh** [comment]
thats our 'generic' problem of oemof/solph: either we are going to be more specific in oemof, or we need more functionalities on the application side...probably both at some point.

**Comment by ckaldemeyer** [comment]
> I think leaving it to the user is not very good...for now it works, we could move the code away from the main file to make it 'clean'.

What do you mean by moving? Putting it into an own module and importing?

> But generally, we should rather tackle the solph/outputlib problem soon. the label 'other' is not great either ;) maybe this one can be 'filling_level' or just level. We really need to work on this...

Yes. This has been annoying me since June, now and we better do it right once now rather then hotfixing. Maybe even directly in a new object replacing the result-dict. So it's not twice a brainfuck..

> thats our 'generic' problem of oemof/solph: either we are going to be more specific in oemof, or we need more functionalities on the application side...probably both at some point.

I think in this case it should be still generic enough to solve it in oemof.

**Comment by eosram** [comment]
Workaround to be non-specific in the post-processing. I'm still renaming the columns with Storage data. I think there must be a way to change the index on the fly without resetting and setting the index, but I couldn't quite figure it out.

**Comment by eosram** [comment]
> Yes. This has been annoying me since June, now and we better do it right once now rather then hotfixing. Maybe even directly in a new object replacing the result-dict. So it's not twice a brainfuck..

Although the solution is more of a hotfix now, solved within renpass_gis. Should this issue stay open?

**Comment by ckaldemeyer** [comment]
> Although the solution is more of a hotfix now, solved within renpass_gis. Should this issue stay open?

Yes!

**Comment by ckaldemeyer** [comment]
I added the possibility to slice arround bus balances with https://github.com/oemof/oemof/pull/277 and added a way to save one csv per bus including all inputs/outputs/other things with https://github.com/oemof/oemof/pull/247

We could use this to simplify the code and make it a bit more usable!
