### ISSUE TITLE
Workingpaper/Documentation (Ideas & Discussion)

### ISSUE THREAD

**Issue by ckaldemeyer** [znes/renpass#20]
Ideas/suggestions can be collected here!

**Comment by wolfbunke** [comment]
At the moment I am working on a latex Report / Documentation form/style. My idea is an additional ZNES serial publication. See: http://www.uni-flensburg.de/eum/downloads/  -> "Diskussionsbeiträge", "Forschungsergebnisse" + new "Methoden und Daten" or similar.

**Comment by ckaldemeyer** [comment]
> At the moment I am working on a latex Report / Documentation form/style. My idea is an additional ZNES serial publication. See: http://www.uni-flensburg.de/eum/downloads/ -> "Diskussionsbeiträge", "Forschungsergebnisse" + new "Methoden und Daten" or similar.

Yep. But I would publish it under the ZNES name and not via the EUF: http://znes-flensburg.de.w0153c74.kasserver.com/publications  (later znes-flensburg.de)

**Comment by wolfbunke** [comment]
yes of course, it is already published under ZNES name. -> ZNES/ EUF or ZNES/ FH But due to the two organisations FS/Uni one institute has to be responsible for ISSN numbering, Impressum , DNB registration (http://www.dnb.de/), etc.  - or two separate publication are needed. But I think this is not really our business...

**Comment by ckaldemeyer** [comment]
> yes of course, it is already published under ZNES name. -> ZNES/ EUF or ZNES/ FH But due to the two organisations FS/Uni one institute has to be responsible for ISSN numbering, Impressum , DNB registration (http://www.dnb.de/), etc. - or two separate publication are needed. But I think this is not really our business...

You're right. But I would only maintain one database for publications and in my opinion I we should do it on the ZNES website (having the uni/fh holding the rights/ISSN).

Also to have a stronger appearance in terms of public relations.

What do you think?

**Comment by wolfbunke** [comment]
Yes, I agree :100: :+1:
