### ISSUE TITLE
Adapt scenario creation via csv reader

### ISSUE THREAD

**Issue by ckaldemeyer** [znes/renpass#24]
See: https://github.com/oemof/oemof/pull/294#issuecomment-291136291

The interface will change with v.0.2.X since the nodes are now created from a dataframe within a scenario class..

**Comment by eosram** [comment]
Hey, thanks for pointing that out and creating the issue!!! In your opinion do you think it's better to break the current cli and include PATH, NAME respectively as it is used instantiating the new Scenario class or do you think it's better to keep NODE_DATA and SEQ_DATA and handling these changes elsewhere?

**Comment by ckaldemeyer** [comment]
> Hey, thanks for pointing that out and creating the issue!!! In your opinion do you think it's better to break the current cli and include PATH, NAME respectively as it is used instantiating the new Scenario class or do you think it's better to keep NODE_DATA and SEQ_DATA and handling these changes elsewhere?

Puhh, good question ;-) From my current point of view I would just leave the CLI as it is.

Maybe @soenkebohm knows more/has a preference here?

**Comment by eosram** [comment]
The CLI has been updated in the course of transitioning to scenario data in datapackage format. The interface only takes a datapackage as non-optional argument. This issue can be closed imho.

**Comment by ckaldemeyer** [comment]
Nice!
