### ISSUE TITLE
Working with renpassgis under windows

### ISSUE THREAD

**Issue by wolfbunke** [znes/renpass#25]
We tried to use use the renpassgis under Windows but couldn't run it. @s3pp @soenkebohm  Do you have any experience?

How is your work flow?

**Comment by simnh** [comment]
I think you need to be a little more specific

**Comment by wolfbunke** [comment]
The main problem was that the Andaconda console couldn't find all packages like pandas. Even all paths been checked. @ClaraBuettner may I ask you to report your issue here?

**Comment by ClaraBuettner** [comment]
I tried to start renpass_gis from Windows console, but I can not import pandas, even if it's installed and works fine when I import it from the iPython console. 
Maybe there is a problem with paths?

**Comment by simnh** [comment]
so you installed anaconda created an environment and you install oemof into that environment. when you start the env and open ipython it does not work? 

can you post the error message from you commandline here?

**Comment by ClaraBuettner** [comment]
When do I have to open iPython? I tried to start renpsssgis from Windows prompt,

(renpass_gis_env) C:\Users\Clara\Documents\GitHub\renpass_gis>renpass_gis_main.py -h

Traceback (most recent call last):
  File "C:\Users\Clara\Documents\GitHub\renpass_gis\renpass_gis_main.py", line 33, in <module>
    import pandas as pd
ImportError: No module named pandas

**Comment by simnh** [comment]
can you open python and try to import e.g. 'from oemof.solph import Flow', if this does not work, renpass and the required packages are not installed correctly inside your env.

**Comment by ClaraBuettner** [comment]
It worked, I don't get an error.

**Comment by simnh** [comment]
and pandas also then?

**Comment by ClaraBuettner** [comment]
yes

**Comment by ClaraBuettner** [comment]
(C:\Users\Clara\Anaconda3) C:\Users\Clara>activate renpass_gis_env

(renpass_gis_env) C:\Users\Clara>cd C:\Users\Clara\Documents\GitHub\renpass_gis

(renpass_gis_env) C:\Users\Clara\Documents\GitHub\renpass_gis>renpass_gis_main.py -h
Traceback (most recent call last):
  File "C:\Users\Clara\Documents\GitHub\renpass_gis\renpass_gis_main.py", line 33, in <module>
    import pandas as pd
ImportError: No module named pandas

(renpass_gis_env) C:\Users\Clara\Documents\GitHub\renpass_gis>pip freeze
appdirs==1.4.3
asn1crypto==0.22.0
CacheControl==0.12.3
certifi==2017.7.27.1
cffi==1.10.0
chardet==3.0.4
colorama==0.3.9
cryptography==2.0.3
cycler==0.10.0
dill==0.2.7.1
distlib==0.2.5
html5lib==0.999999999
idna==2.6
lockfile==0.12.2
matplotlib==2.1.0
msgpack-python==0.4.8
nose==1.3.7
numpy==1.13.3
oemof==0.1.4
packaging==16.8
pandas==0.20.3
ply==3.10
progress==1.3
pycparser==2.18
Pyomo==5.2
pyOpenSSL==17.2.0
pyparsing==2.2.0
pyreadline==2.1
PySocks==1.6.7
python-dateutil==2.6.1
pytz==2017.2
PyUtilib==5.5.1
requests==2.18.4
six==1.10.0
urllib3==1.22
webencodings==0.5.1
win-inet-pton==1.0.1
wincertstore==0.2

That's what I typed in Anaconda prompt.

**Comment by ckaldemeyer** [comment]
> C:\Users\Clara\Anaconda3) C:\Users\Clara>activate renpass_gis_env
> 
> (renpass_gis_env) C:\Users\Clara>cd C:\Users\Clara\Documents\GitHub\renpass_gis
> 
> (renpass_gis_env) C:\Users\Clara\Documents\GitHub\renpass_gis>renpass_gis_main.py -h
> Traceback (most recent call last):
> File "C:\Users\Clara\Documents\GitHub\renpass_gis\renpass_gis_main.py", line 33, in 
> import pandas as pd
> ImportError: No module named pandas

Try to open a Python/IPython console within the environment you want to use.

Then, type:

    import pandas as pd

If you get no errors and run renpass_gis using one of these consoles located in e.g. `path_to_anaconda/bin/python3.5` it should work. Otherwise you are using a wrong environment.

Of course, the oemof package also has to be installed..

**Comment by ClaraBuettner** [comment]
It works now! For some reason I had installed Python 3 and Python 2. After uninstalling Python 2 it worked. Thanks for your help!
