### ISSUE TITLE
v0.1 ? 

### ISSUE THREAD

**Issue by simnh** [znes/renpass#3]
I think we can clean up this repository and release the v0.1 soon (maybe when data stuff is clarified). For me it makes sense, as it's based on oemof.solph v0.1 which has been tested quit a lot and works 
fine. We could do some polishing for the first version. But I to not think we should start with 0.0.1...

What do you think: 
@ckaldemeyer, @s3pp  

Some one else who is contribution here?

**Comment by ckaldemeyer** [comment]
> I think we can clean up this repository and release the v0.1 soon (maybe when data stuff is clarified). For me it makes sense, as it's based on oemof.solph v0.1 which has been tested quit a lot and works 
> fine. We could do some polishing for the first version. But I to not think we should start with 0.0.1...

Absolutely!

**Comment by eosram** [comment]
I agree. version 0.1 is fine for me.

> I think we can clean up this repository and release the v0.1 soon (maybe when data stuff is clarified).

I will meet with Martin Jahn this week as a starting point. The goal of the meeting is to write down open questions with regard to data licensing of renpass_gis energy scenarios.

**Comment by ckaldemeyer** [comment]
I just released by accident since I merged the PR accidentially in the master. But I think this is absolutely o.k.

**Comment by ckaldemeyer** [comment]
Well, maybe not. We have to add a flag, etc.

Who will do it?

**Comment by simnh** [comment]
what? adding a tag?

**Comment by simnh** [comment]
a tag

**Comment by ckaldemeyer** [comment]
yes, flag/tag/marker, ... :)

**Comment by ckaldemeyer** [comment]
Have a look at: https://github.com/znes/renpass_gis

Is there missing something?

At the moment, the only thing that has to be worked on is the chapter "usage".

**Comment by ckaldemeyer** [comment]
I'll write the mail with our plans tomorrow and @s3pp will streamline the command line interface.

We are planning to release the first version next week; even without the refactored result dataframe (unstack all, renamed storage labels, ...).

We can then still do another release quite quickly. I think it just makes sense to work step by step and not wait until everything is "perfect" which will never be the case anyway..
