### ISSUE TITLE
Fix attribute facade naming capacity / power

### ISSUE THREAD

**Issue by simnh** [znes/renpass#36]
For storages capacity refers to energy whereas for powerplant it refers to power. This should be fixed as it is 1) kind of confusing 2) more importantly cause trouble for plotting e.g. installed power / capacities...

Any ideas?

**Comment by eosram** [comment]
I would suggest establishing a clear distinction between these by using nominal_power instead of capacity (rated, nameplate, installed, generation capacity). Then we are able to still use capacity with a meaning of maximum storage capacity without confusion. What's your opinion @soenkebohm ?

**Comment by simnh** [comment]
Maybe we can sit together and go trough **all** attributes and decide on that. I woul like to decide that on the datapackage reader. So I suggest coming up with the documentation for the (energy) datapackage 'standard' / naming convention / data model. And then use this for the facades as well. In the datapackage reader we might then also set the default attribute mapping for some things to 1:n, meaning: nominal_power maps to power, max_power, installed_power... etc. 

Maybe we can do this before your vacation @s3pp

**Comment by eosram** [comment]
Yes, we can do that.

**Comment by simnh** [comment]
Fixed it for now, will probably come up again...
