### ISSUE TITLE
Overall description?

### ISSUE THREAD

**Issue by ckaldemeyer** [znes/renpass#38]
Thanks for all your effort. But shouldn't the README contain a description what renpass is before giving instructions how to install it, ... ?

It doesn't need figures but I think otherwise people are quite lost as I have experienced quite some questions in the past even with a for my opinion quite extensive description what it actually is.

**Comment by eosram** [comment]
I guess, you're right : ). What about:

_From a user's perspective renpass is the executable renpass.py, a command-line tool, that is called to read and process input data in a [pre-defined tabular datapackage](https://github.com/znes/datapackage-utilities#data-model-description) format representing a simplified supply energy system, subsequently model the cost-minimal dispatch of said system and to write back optimization results._

Maybe if we distinguish between developers and users perspective, we don't have to go into more detail for the moment.

**Comment by simnh** [comment]
Thanks for the feedback :-) 

If you want to supply some text, feel free to open a pull request. As mentioned the design goal differs quite significantly from what it is now, so we will surely provide more detailed infos once the software evolves...

**Comment by ckaldemeyer** [comment]
> Thanks for the feedback :-)
> 
> If you want to supply some text, feel free to open a pull request. As mentioned the design goal differs quite significantly from what it is now, so we will surely provide more detailed infos once the software evolves...

I won't contribute anything but just give feedback as I have experienced that "normal users" are even overchallenged even if a quite detailed description is provided. But good effort! Keep going ;-)

**Comment by simnh** [comment]
We will work and improve this along with code and functionality improvements!
