### ISSUE TITLE
Main repository responsibilities

### ISSUE THREAD

**Issue by simnh** [znes/renpass#4]
Should we decide on some main responsibilities are at least on who is involved in decision making processes inside this repository? 

* Who to assign
* With whom are pull request dicussed
* Set some guidelines for contribution (feature branches etc)
....

**Comment by ckaldemeyer** [comment]
> Should we decide on some main responsibilities are at least on who is involved in decision making processes inside this repository?

Good idea! But this decision is part of the MoVe meetings and should only be discussed there.

Would it make sense that one of you and Clemens joins again as you now stay longer and both are heavily involved in the modelling group? I think it would make sense.

**Comment by simnh** [comment]
You mean MoVe or renpass in general? 

Yes I agree, for the next 4 month it will probably be me for both: renpass repo, (development especially the eGo prespective) and MoVe (maybe sometimes)...

**Comment by ckaldemeyer** [comment]
> You mean MoVe or renpass in general?
> Yes I agree, for the next 4 month it will probably be me for both: renpass repo, (development especially the eGo prespective) and MoVe (maybe sometimes)...

Eigentlich mehr renpass.

Die Verantwortlichkeit für Modelle also gerade nur renpass liegt derzeit gerade bei Martin. Dann würde ich vorschlagen, dass du das evtl. mit ihm zusammen übernimmst. Alles renpass-mäßig geplante wollten wir aber ab jetzt zusammen im MoVe entscheiden, um "Projektspezifisches Hijacken" zu verhindern und wirklich voneinander zu profitieren.

Auch wenn ich glaube, dass du an erster Stelle daran interessiert bist es so zu entwickeln, dass andere es nutzen können, sollten wir das vorher abstimmen. Sonst gibt es nachher wieder ein Systemmodell, dass nicht zu anderen Projekten passt und wir drehen uns im Kreis..

**Comment by ckaldemeyer** [comment]
Im Übrigens glaube ich, dass es gerade auch eine Chanche ist mit verschiedenen Projekten daran zu arbeiten bzw. sich abzusprechen

**Comment by simnh** [comment]
BTW: Vielleicht können wir je auch einfach mal nen HiWi anstellen, der das Repository hier schick macht. Mit plots etc.(idealerweise jemand der dann auch damit eine Arbeit damit durchführt z.B. MA...)

**Comment by ckaldemeyer** [comment]
> BTW: Vielleicht können wir je auch einfach mal nen HiWi anstellen, der das Repository hier schick macht. Mit plots etc.(idealerweise jemand der dann auch damit eine Arbeit damit durchführt z.B. MA...)

Klar, kann man alles machen und die Idee (nur Arbeit schreiben und Szenarien verbessern) stand schon häufiger im Raum. Würde ich dann aber auch MoVe-mäßig planen..

**Comment by eosram** [comment]
Ich finde, es kann für MoVe nur von Vorteil sein, wenn renpass_gis und dessen Weiterentwicklung oft zum Thema gemacht wird. Innerhalb der Treffen des MoVe sollte m.E. auch konkret über alle größeren Änderungen (welches Feature wird bspw. Teil des Master?) und die Verantwortlichkeiten in diesem repository entschieden werden.

Über bspw. die Einhaltung von Richtlinien zur Mitarbeit können m.E. der/die Modelverantwortlichen entscheiden. Meiner Meinung nach sollten die Mitglieder des MoVe bei einem nächsten Treffen zumindest informiert werden.

**Comment by simnh** [comment]
Hatte eigentlich erwartet, dass es jemanden gibt der sich bereit erklärt das repository etwas im Blick zu haben. So war das issue gemeint...hat sich etwas anders entwickelt, daher schließe ich das jetzt. Der Rest dann per Mail.

**Comment by ckaldemeyer** [comment]
Eigentlich war

**Comment by ckaldemeyer** [comment]
Ich kopiere die Mail mal hier rein, damit nix verloren geht aus der Diskussion:

> > Über bspw. die Einhaltung von Richtlinien zur Mitarbeit können m.E. der/die Modelverantwortlichen entscheiden. Meiner Meinung nach sollten die Mitglieder des MoVe bei einem nächsten Treffen zumindest informiert werden.
> 
> Ich denke nicht, dass wir das MoVe treffen überstrapazieren sollten
> (zumindest nicht in seiner jetzigen Form. Meiner Meinung nach sollte das
> MoVe zur Abstimmung und zum Informationsauttuasch dienen und der Rest
> muss ohnehin auf Mitarbeiterebene geklärt werden. Etwas anderes geben
> die Strukturen einfach nicht her....siehe letztes Treffen).

Genau diese Abstimmung (Weiterentwicklung von App-Features, Roadmap, Verantwortlichkeiten, ...) sollte meiner Meinung nach -zumindest in der groben Form- innerhalb des MoVe passieren. Feinheiten kann man da natürlich nicht abstimmen aber grobe **gemeinsame** Linien definieren, um unnötige Redundanzen und zu projektspezifische Anpassungen zu vermeiden.

> Richtlinien und Ideen für Modelle wollen schließlich auch entwickelt
> werden und bei MoVe wird das nicht getan. Es braucht einfach eine Person
> oder Gruppe, die sich für dieses Repository (renpass) verantwortlich
> fühlt...ansonsten denke ich kriegen wir hier nur einen Haufen
> feature-branches....und die Frage ist, wer das ist. Dazu gehört einfach
> auch im Blick zu haben, was von anderen NutzerInnen zurückgespielt
> werden kann in die app und nach oemof....Meinetwegen kann das auch bei
> dem MoVe geklärt werden....wenn es sein muss.
> Schönen Abend!

Modelle werden dort nicht entwickelt, spezifische Richtlinien auch nicht, aber grobe Leitlinien auf jeden Fall. Und das mit den Feature-Branches passiert genau dann wenn man sich nicht abstimmt.

Ich sehe es so, dass man dort bis zu einem bestimmten Punkt den gemeinsamen "dev/master" plant, von dem dann ggf. projektspezifisch abgezweigt werden kann.

Und die verantwortliche Person sollte alle "Stakeholder-Projekte" (bei renpass gerade ENKF, eGo, MENA) im Blick haben und nach Abstimmung berücksichtigen. Eigentlich ist derjenige gerade Martin. Aber wir sollten uns nicht unnötig selbst Steine in den Weg lesen und wenn jemand anders das sinnvollerweise übernehmen will, können wir ja darüber reden..

**Comment by eosram** [comment]
> Genau diese Abstimmung (Weiterentwicklung von App-Features, Roadmap, Verantwortlichkeiten, ...) sollte meiner Meinung nach -zumindest in der groben Form- innerhalb des MoVe passieren. Feinheiten kann man da natürlich nicht abstimmen aber grobe **gemeinsame** Linien definieren, um unnötige Redundanzen und zu projektspezifische Anpassungen zu vermeiden.

Ich bin auch der Meinung, dass die grobe Abstimmung zwischen den Projekten bezogen auf renpass_gis im MoVe passieren oder zumindest dort regelmäßig kommuniziert werden sollte. Und  damit eben auch das, was zurückgespielt werden kann. Es ist meiner Meinung nach von Vorteil, wenn auch die Modellierer, die renpass_gis derzeit nicht gezielt nutzen, zumindest über die weitere Entwicklung von renpass_gis im Bilde sind und mitdiskutieren können.

Trotzdem bin ich auch der Auffassung, dass es für dieses Repository Verantwortliche geben muss. Das bin derzeit wohl ich : ). Ich finde, dass das auch im MoVe besprochen werden kann.

Denn es wäre m.E. von Vorteil, wenn je ein Mitarbeiter von den derzeit drei an der Entwicklung/Anwendung beteiligten Projekte verantwortlich wäre. Dazu zähle ich auch : ). Entscheidungen können unter Vorbehalt auch in dieser Gruppe getroffen werden, wichtig ist m.E., dass diese Entscheidungen im MoVe noch einmal zur Disposition gestellt werden.

**Comment by ckaldemeyer** [comment]
Ich habe gestern schon mit Simon telefoniert. Die Idee war, dass wir uns nächste Woche mal nach dem Mittagessen zusammensetzen und eine Struktur überlegen, die wir dann im MoVe vorschlagen. Quasi "Management-by-Proposal", wie wir das in DK mal hatten. 

Ich denke, dass ist derzeit der einzige Weg, um da - vor allem zeitnah - eine Linie reinzubekommen, denn sonst wird da vermutlich bis in's neue Jahr nichts passieren..

**Comment by ckaldemeyer** [comment]
Achso, was ich eigentlich sagen wollte: Die Idee wäre dann natürlich das zu dritt zu machen!

**Comment by eosram** [comment]
Ok, find ich gut!

**Comment by simnh** [comment]
Ok, I used realized what the problem is: We need (znes- internally) people that are responsible, so that everyone who gets a question regarding renpass-gis can be directly sent to these guys. Otherwise information is lost, synergies are not used and more importantly, answers might be not in line with our defined  structure, workflows etc.

To conclude: We should inform alle znes-people, that person x.x and x.x are the persons to ask questions regarding the repository. 'floor'-communication is important but someone needs to keep track of the developments...

**Comment by ckaldemeyer** [comment]
> Ok, I used realized what the problem is: We need (znes- internally) people that are responsible, so that everyone who gets a question regarding renpass-gis can be directly sent to these guys. Otherwise information is lost, synergies are not used and more importantly, answers might be not in line with our defined structure, workflows etc.
> 
> To conclude: We should inform alle znes-people, that person x.x and x.x are the persons to ask questions regarding the repository. 'floor'-communication is important but someone needs to keep track of the developments...

Wollen wir uns wegen des Strukturvorschlags/Papers und den anderen offenen Punkten eigentlich live treffen? Ich finde die Diskussion hier gerade nicht wirklich zielführend

**Comment by ckaldemeyer** [comment]
Wobei ich dem von dir Geschriebenen durchaus zustimme..

**Comment by ckaldemeyer** [comment]
I think this one was solved with the last meeting..
