### ISSUE TITLE
Documentation file

### ISSUE THREAD

**Issue by ckaldemeyer** [znes/renpass#5]
Where is actually the documentation file? And is it finished?

I couldn't find it on dev and meanwhile -as some people want to use renpass_gis and keep on asking questions- it would be good to have it as a reference.

**Comment by eosram** [comment]
Do you mean the renpass_gis_documentation.rst, which mostly describes the scenarios and it's sources. In my view it is not so much of a documentation of renpass_gis and belongs to the energy scenarios. That is why I haven't committed the file yet. It's still accessable on our server. I could commit it though?

**Comment by ckaldemeyer** [comment]
> Do you mean the renpass_gis_documentation.rst, which mostly describes the scenarios and it's sources. In my view it is not so much of a documentation of renpass_gis and belongs to the energy scenarios. That is why I haven't committed the file yet. It's still accessable on our server. I could commit it though?

It would be great as some people of the University of Kassel are checking oemof atm. and keep on asking questions that could be answered with the documentation.

**Comment by ckaldemeyer** [comment]
It would be great if someone pushes the button and publishes the whole thing ;)
