### ISSUE TITLE
CSV-reader documentation 

### ISSUE THREAD

**Issue by simnh** [znes/renpass#6]
Sönke is currently using renpassgis and will probably have some important input on the csv-reader user perspective. We should use this momentum to create a description on how to use this one. Maybe build it inside oemof and link it here inside this repository. This is of course linked to #5

**Comment by ckaldemeyer** [comment]
@soenkebohm : Can you already make some suggestions?

**Comment by soenkebohm** [comment]
I am currently preparing for our workshop, e.g. working on presentations. During the workshop we will guide through the installation process, explain what scripts and data can be adjusted, and hopefully will have working examples (scenarios) at the end. Our aim is to enable our participants to get an understanding of and work with the model. As our participants are not yet familiar with the model, we try to keep everything as user-friendly as possible. 
As we are pretty busy these days and time is running out it might be best to have another update after our workshop.

**Comment by ckaldemeyer** [comment]
> I am currently preparing for our workshop, e.g. working on presentations. During the workshop we will guide through the installation process, explain what scripts and data can be adjusted, and hopefully will have working examples (scenarios) at the end. Our aim is to enable our participants to get an understanding of and work with the model. As our participants are not yet familiar with the model, we try to keep everything as user-friendly as possible.
As we are pretty busy these days and time is running out it might be best to have another update after our workshop.

O.k.. So I suggest we just postpone this for the next milestone!

**Comment by simnh** [comment]
CSV-reade has been replaced by datapackge reader
