### ISSUE TITLE
renpass_gis-data repository ?

### ISSUE THREAD

**Issue by simnh** [znes/renpass#7]
Should we have a renpass-gis data repository? We could then have different scenarios there structured by folders. Also this one could be private or on the uni server, so that we do not have any problems with data licensing. Then, maybe we do not end up with 20 feature branches and the feature branches can be used for code development. We then need to make sure that all scenarios work with renpassgis version x.x.

**Comment by ckaldemeyer** [comment]
> Should we have a renpass-gis data repository? We could then have different scenarios there structured by folders. Also this one could be private or on the uni server, so that we do not have any problems with data licensing. Then, maybe we do not end up with 20 feature branches and the feature branches can be used for code development. We then need to make sure that all scenarios work with renpassgis version x.x.

Coole Idee. Das legt auch gleich die Schnittstelle/Kompatibilität fest!

Wenn es in die weitere Planung geht, würde ich mich gerne mal live treffen. Ich habe das Gefühl, dass ich garnicht mehr auf dem Laufenden bin, was renpassG!S bzw. die Thematik um die Veröffentlichung angeht, wer involviert ist, woran es hängt, ...

**Comment by eosram** [comment]
Als wir das letzte Mal dazu telefoniert haben, sind Cord und ich zu dem Schluss gekommen, dass ein privates Repository auf GitHub besser sei als die Uni - Server Lösung. Ich denke, dass ist richtig ist. Wir waren so verblieben, dass mit Ilja und Olav zu beprechen (Kosten, Eigentümer des Repositories), wenn ich mich richtig entsinne : ). Oder? Naja, das können wir ja Mittwoch auch nochmal besprechen. Eine Uni - Server Lösung mit Passwort geschütztem Repository könnte ich mit Günni absprechen. Das ginge ja recht schnell, denke ich.

**Comment by ckaldemeyer** [comment]
> Als wir das letzte Mal dazu telefoniert haben, sind Cord und ich zu dem Schluss gekommen, dass ein privates Repository auf GitHub besser sei als die Uni - Server Lösung. Ich denke, dass ist richtig ist. Wir waren so verblieben, dass mit Ilja und Olav zu beprechen (Kosten, Eigentümer des Repositories), wenn ich mich richtig entsinne : ). Oder? Naja, das können wir ja Mittwoch auch nochmal besprechen. Eine Uni - Server Lösung mit Passwort geschütztem Repository könnte ich mit Günni absprechen. Das ginge ja recht schnell, denke ich.

Das hatte ich schon wieder total vergessen.. Ein privates github-Repo fände ich auf jeden Fall besser als den VN-Server! Alleine schon, falls man das mal fix umziehen/veröffentlichen möchte und um nicht wieder doppelte Rechtestrukturen, etc. pflegen zu müssen.

**Comment by eosram** [comment]
We could also apply for a discount: https://education.github.com/discount_requests/new !

**Comment by ckaldemeyer** [comment]
@s3pp, @wolfbunke : Could you track the progress here?

**Comment by eosram** [comment]
Costs can be covered with project funds according to our project management organisation. Wolf now will buy the subscription.

**Comment by ckaldemeyer** [comment]
:+1:

**Comment by eosram** [comment]
We created a public and private data repository within the ZNES organisation available at [FlEnS](https://github.com/znes/FlEnS), [cFlEnS](https://github.com/znes/cFlEnS). There are no subscription cost, because of the GitHub Education program.
