### ISSUE TITLE
Change from python script to command line program

### ISSUE THREAD

**Issue by ckaldemeyer** [znes/renpass#9]
Should we format the whole thing into as a Python programm (if __name__ ...) to be a bit more standard?

We need it for the tests anyway..

**Comment by ckaldemeyer** [comment]
The solver should also be passable via the command line

**Comment by simnh** [comment]
I think a program would be good, but we should also have an easy way to use it with scripting....do not know how to do it...

**Comment by ckaldemeyer** [comment]
> I think a program would be good, but we should also have an easy way to use it with scripting....do not know how to do it...

We are already changing it to a command line program. @s3pp is making the changes and it will get even leaner when the handling (renaming) of storage labels is not necessary any more with the result RDF improvements. 

I think this way together with a better description of the csv reader (maybe a link) should be o.k..

**Comment by simnh** [comment]
ah ok, cool!

**Comment by simnh** [comment]
Can we have a pull request for this one then?

**Comment by ckaldemeyer** [comment]
> Can we have a pull request for this one then?

@s3pp will open one

**Comment by eosram** [comment]
#12
